[package]
name = "bifrost-package-manager"
version = "1.1.1"
authors = ["javanhut@carrionlang.com"]
description = "Carrion Package Manager for installing new packages"
license = "MIT"
repository = "https://github.com/javanhut/bifrost"
keywords = ["package-manager", "carrion", "build-tool"]

[package.metadata]
main = "cmd/bifrost/main.go"
include = ["internal/**/*", "go.mod", "go.sum", "LICENSE", "README.md"]

[dependencies]
carrionlang = ">=0.1.6, <1.0.0"
json-utils = "^0.3.5"